name: Deploy Just the Docs Wiki

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Configura a variável de ambiente para usar o Node moderno e evitar os avisos
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # 1. Altere a versão do Ruby para 3.4 (para bater com o seu ambiente local do Arch)
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4' 
        bundler-cache: true # Ativa o cache automático para acelerar o build de 11s

    # 2. Executa a instalação de dependências isolada pelo Bundler
    - name: Install Dependencies
      run: |
        bundle config set --local path 'vendor/bundle'
        bundle install

    # 3. Compila o site do Just the Docs
    - name: Build Website
      run: bundle exec jekyll build
